[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  VITE_API_URL = "Backend API URL (e.g., https://your-backend.onrender.com/api)"
  VITE_TELEGRAM_BOT_USERNAME = "Your Telegram bot username (optional)"